/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as ESlugCheckoutRouteImport } from './routes/e.$slug.checkout'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as ApiGopayNotifyRouteImport } from './routes/api.gopay.notify'
import { Route as ApiOrdersOrderIdTicketsTicketIdRouteImport } from './routes/api.orders.$orderId.tickets.$ticketId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/e/$slug/',
  path: '/e/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugCheckoutRoute = ESlugCheckoutRouteImport.update({
  id: '/e/$slug/checkout',
  path: '/e/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const ApiGopayNotifyRoute = ApiGopayNotifyRouteImport.update({
  id: '/api/gopay/notify',
  path: '/api/gopay/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdTicketsTicketIdRoute =
  ApiOrdersOrderIdTicketsTicketIdRouteImport.update({
    id: '/api/orders/$orderId/tickets/$ticketId',
    path: '/api/orders/$orderId/tickets/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/order/$id': typeof OrderIdRoute
  '/app/': typeof AppIndexRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/order/$id': typeof OrderIdRoute
  '/app': typeof AppIndexRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/order/$id': typeof OrderIdRoute
  '/app/': typeof AppIndexRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/order/$id'
    | '/app/'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug/'
    | '/api/orders/$orderId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/order/$id'
    | '/app'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug'
    | '/api/orders/$orderId/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/order/$id'
    | '/app/'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug/'
    | '/api/orders/$orderId/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrderIdRoute: typeof OrderIdRoute
  ApiGopayNotifyRoute: typeof ApiGopayNotifyRoute
  ESlugCheckoutRoute: typeof ESlugCheckoutRoute
  ESlugIndexRoute: typeof ESlugIndexRoute
  ApiOrdersOrderIdTicketsTicketIdRoute: typeof ApiOrdersOrderIdTicketsTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/e/$slug'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/checkout': {
      id: '/e/$slug/checkout'
      path: '/e/$slug/checkout'
      fullPath: '/e/$slug/checkout'
      preLoaderRoute: typeof ESlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/gopay/notify': {
      id: '/api/gopay/notify'
      path: '/api/gopay/notify'
      fullPath: '/api/gopay/notify'
      preLoaderRoute: typeof ApiGopayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/tickets/$ticketId': {
      id: '/api/orders/$orderId/tickets/$ticketId'
      path: '/api/orders/$orderId/tickets/$ticketId'
      fullPath: '/api/orders/$orderId/tickets/$ticketId'
      preLoaderRoute: typeof ApiOrdersOrderIdTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsNewRoute: AppEventsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrderIdRoute: OrderIdRoute,
  ApiGopayNotifyRoute: ApiGopayNotifyRoute,
  ESlugCheckoutRoute: ESlugCheckoutRoute,
  ESlugIndexRoute: ESlugIndexRoute,
  ApiOrdersOrderIdTicketsTicketIdRoute: ApiOrdersOrderIdTicketsTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
