/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ApiCheckinRouteImport } from './routes/api.checkin'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as AdminOrganizersIndexRouteImport } from './routes/admin.organizers.index'
import { Route as ESlugCheckoutRouteImport } from './routes/e.$slug.checkout'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as ApiGopayNotifyRouteImport } from './routes/api.gopay.notify'
import { Route as AdminOrganizersOrganizerIdRouteImport } from './routes/admin.organizers.$organizerId'
import { Route as AppEventsEventIdSalesRouteImport } from './routes/app.events.$eventId.sales'
import { Route as AppEventsEventIdCheckinRouteImport } from './routes/app.events.$eventId.checkin'
import { Route as ApiEventsEventIdSalesCsvRouteImport } from './routes/api.events.$eventId.sales-csv'
import { Route as ApiOrdersOrderIdTicketsTicketIdRouteImport } from './routes/api.orders.$orderId.tickets.$ticketId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinRoute = ApiCheckinRouteImport.update({
  id: '/api/checkin',
  path: '/api/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/e/$slug/',
  path: '/e/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizersIndexRoute = AdminOrganizersIndexRouteImport.update({
  id: '/organizers/',
  path: '/organizers/',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugCheckoutRoute = ESlugCheckoutRouteImport.update({
  id: '/e/$slug/checkout',
  path: '/e/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const ApiGopayNotifyRoute = ApiGopayNotifyRouteImport.update({
  id: '/api/gopay/notify',
  path: '/api/gopay/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizersOrganizerIdRoute =
  AdminOrganizersOrganizerIdRouteImport.update({
    id: '/organizers/$organizerId',
    path: '/organizers/$organizerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AppEventsEventIdSalesRoute = AppEventsEventIdSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdCheckinRoute = AppEventsEventIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const ApiEventsEventIdSalesCsvRoute =
  ApiEventsEventIdSalesCsvRouteImport.update({
    id: '/api/events/$eventId/sales-csv',
    path: '/api/events/$eventId/sales-csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersOrderIdTicketsTicketIdRoute =
  ApiOrdersOrderIdTicketsTicketIdRouteImport.update({
    id: '/api/orders/$orderId/tickets/$ticketId',
    path: '/api/orders/$orderId/tickets/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/order/$id': typeof OrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/admin/organizers/': typeof AdminOrganizersIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/order/$id': typeof OrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/admin/organizers': typeof AdminOrganizersIndexRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/order/$id': typeof OrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/admin/organizers/': typeof AdminOrganizersIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/register'
    | '/admin/events'
    | '/admin/orders'
    | '/api/checkin'
    | '/order/$id'
    | '/admin/'
    | '/app/'
    | '/admin/organizers/$organizerId'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/admin/organizers/'
    | '/e/$slug/'
    | '/api/events/$eventId/sales-csv'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/sales'
    | '/api/orders/$orderId/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/events'
    | '/admin/orders'
    | '/api/checkin'
    | '/order/$id'
    | '/admin'
    | '/app'
    | '/admin/organizers/$organizerId'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/admin/organizers'
    | '/e/$slug'
    | '/api/events/$eventId/sales-csv'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/sales'
    | '/api/orders/$orderId/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/register'
    | '/admin/events'
    | '/admin/orders'
    | '/api/checkin'
    | '/order/$id'
    | '/admin/'
    | '/app/'
    | '/admin/organizers/$organizerId'
    | '/api/gopay/notify'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/admin/organizers/'
    | '/e/$slug/'
    | '/api/events/$eventId/sales-csv'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/sales'
    | '/api/orders/$orderId/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiCheckinRoute: typeof ApiCheckinRoute
  OrderIdRoute: typeof OrderIdRoute
  ApiGopayNotifyRoute: typeof ApiGopayNotifyRoute
  ESlugCheckoutRoute: typeof ESlugCheckoutRoute
  ESlugIndexRoute: typeof ESlugIndexRoute
  ApiEventsEventIdSalesCsvRoute: typeof ApiEventsEventIdSalesCsvRoute
  ApiOrdersOrderIdTicketsTicketIdRoute: typeof ApiOrdersOrderIdTicketsTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkin': {
      id: '/api/checkin'
      path: '/api/checkin'
      fullPath: '/api/checkin'
      preLoaderRoute: typeof ApiCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/e/$slug'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizers/': {
      id: '/admin/organizers/'
      path: '/organizers'
      fullPath: '/admin/organizers/'
      preLoaderRoute: typeof AdminOrganizersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/checkout': {
      id: '/e/$slug/checkout'
      path: '/e/$slug/checkout'
      fullPath: '/e/$slug/checkout'
      preLoaderRoute: typeof ESlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/gopay/notify': {
      id: '/api/gopay/notify'
      path: '/api/gopay/notify'
      fullPath: '/api/gopay/notify'
      preLoaderRoute: typeof ApiGopayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizers/$organizerId': {
      id: '/admin/organizers/$organizerId'
      path: '/organizers/$organizerId'
      fullPath: '/admin/organizers/$organizerId'
      preLoaderRoute: typeof AdminOrganizersOrganizerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/events/$eventId/sales': {
      id: '/app/events/$eventId/sales'
      path: '/sales'
      fullPath: '/app/events/$eventId/sales'
      preLoaderRoute: typeof AppEventsEventIdSalesRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/checkin': {
      id: '/app/events/$eventId/checkin'
      path: '/checkin'
      fullPath: '/app/events/$eventId/checkin'
      preLoaderRoute: typeof AppEventsEventIdCheckinRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/api/events/$eventId/sales-csv': {
      id: '/api/events/$eventId/sales-csv'
      path: '/api/events/$eventId/sales-csv'
      fullPath: '/api/events/$eventId/sales-csv'
      preLoaderRoute: typeof ApiEventsEventIdSalesCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/tickets/$ticketId': {
      id: '/api/orders/$orderId/tickets/$ticketId'
      path: '/api/orders/$orderId/tickets/$ticketId'
      fullPath: '/api/orders/$orderId/tickets/$ticketId'
      preLoaderRoute: typeof ApiOrdersOrderIdTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizersOrganizerIdRoute: typeof AdminOrganizersOrganizerIdRoute
  AdminOrganizersIndexRoute: typeof AdminOrganizersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizersOrganizerIdRoute: AdminOrganizersOrganizerIdRoute,
  AdminOrganizersIndexRoute: AdminOrganizersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdCheckinRoute: typeof AppEventsEventIdCheckinRoute
  AppEventsEventIdSalesRoute: typeof AppEventsEventIdSalesRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdCheckinRoute: AppEventsEventIdCheckinRoute,
  AppEventsEventIdSalesRoute: AppEventsEventIdSalesRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiCheckinRoute: ApiCheckinRoute,
  OrderIdRoute: OrderIdRoute,
  ApiGopayNotifyRoute: ApiGopayNotifyRoute,
  ESlugCheckoutRoute: ESlugCheckoutRoute,
  ESlugIndexRoute: ESlugIndexRoute,
  ApiEventsEventIdSalesCsvRoute: ApiEventsEventIdSalesCsvRoute,
  ApiOrdersOrderIdTicketsTicketIdRoute: ApiOrdersOrderIdTicketsTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
