/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ObchodnePodmienkyRouteImport } from './routes/obchodne-podmienky'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as AppRouteImport } from './routes/app'
import { Route as AkoToFungujeRouteImport } from './routes/ako-to-funguje'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PosReceiptOrderIdRouteImport } from './routes/pos-receipt.$orderId'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as AppSettlementsRouteImport } from './routes/app.settlements'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDevelopersRouteImport } from './routes/app.developers'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiCheckinRouteImport } from './routes/api.checkin'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as AdminOrganizersIndexRouteImport } from './routes/admin.organizers.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as ESlugEmbedRouteImport } from './routes/e.$slug.embed'
import { Route as ESlugCheckoutRouteImport } from './routes/e.$slug.checkout'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as ApiV1OrdersRouteImport } from './routes/api.v1.orders'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api.v1.openapi[.]json'
import { Route as ApiV1MeRouteImport } from './routes/api.v1.me'
import { Route as ApiV1EventsRouteImport } from './routes/api.v1.events'
import { Route as ApiOgSlugRouteImport } from './routes/api.og.$slug'
import { Route as ApiGopayNotifyRouteImport } from './routes/api.gopay.notify'
import { Route as ApiCronProcessWebhooksRouteImport } from './routes/api.cron.process-webhooks'
import { Route as ApiCronProcessWaitlistRouteImport } from './routes/api.cron.process-waitlist'
import { Route as ApiCronProcessRefundsRouteImport } from './routes/api.cron.process-refunds'
import { Route as ApiCronProcessEmailRouteImport } from './routes/api.cron.process-email'
import { Route as ApiCronIssueInvoicesRouteImport } from './routes/api.cron.issue-invoices'
import { Route as AdminOrganizersOrganizerIdRouteImport } from './routes/admin.organizers.$organizerId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/app.events.$eventId.index'
import { Route as AppEventsEventIdSalesRouteImport } from './routes/app.events.$eventId.sales'
import { Route as AppEventsEventIdPosSummaryRouteImport } from './routes/app.events.$eventId.pos-summary'
import { Route as AppEventsEventIdPosRouteImport } from './routes/app.events.$eventId.pos'
import { Route as AppEventsEventIdManualOrderRouteImport } from './routes/app.events.$eventId.manual-order'
import { Route as AppEventsEventIdGuestlistRouteImport } from './routes/app.events.$eventId.guestlist'
import { Route as AppEventsEventIdCheckinRouteImport } from './routes/app.events.$eventId.checkin'
import { Route as ApiV1EventsIdRouteImport } from './routes/api.v1.events.$id'
import { Route as ApiSettlementsSettlementIdPdfRouteImport } from './routes/api.settlements.$settlementId.pdf'
import { Route as ApiEventsEventIdSalesCsvRouteImport } from './routes/api.events.$eventId.sales-csv'
import { Route as ApiEventsEventIdAttendeesCsvRouteImport } from './routes/api.events.$eventId.attendees-csv'
import { Route as ApiAdminExportOrganizersDotcsvRouteImport } from './routes/api.admin.export.organizers[.]csv'
import { Route as ApiAdminExportOrdersDotcsvRouteImport } from './routes/api.admin.export.orders[.]csv'
import { Route as AppEventsEventIdOrdersOrderIdRouteImport } from './routes/app.events.$eventId.orders.$orderId'
import { Route as ApiV1EventsIdTicketsRouteImport } from './routes/api.v1.events.$id.tickets'
import { Route as ApiOrdersOrderIdTicketsTicketIdRouteImport } from './routes/api.orders.$orderId.tickets.$ticketId'
import { Route as ApiOrdersOrderIdTicketsTicketIdPassRouteImport } from './routes/api.orders.$orderId.tickets.$ticketId.pass'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ObchodnePodmienkyRoute = ObchodnePodmienkyRouteImport.update({
  id: '/obchodne-podmienky',
  path: '/obchodne-podmienky',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AkoToFungujeRoute = AkoToFungujeRouteImport.update({
  id: '/ako-to-funguje',
  path: '/ako-to-funguje',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PosReceiptOrderIdRoute = PosReceiptOrderIdRouteImport.update({
  id: '/pos-receipt/$orderId',
  path: '/pos-receipt/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettlementsRoute = AppSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersRoute = AppDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckinRoute = ApiCheckinRouteImport.update({
  id: '/api/checkin',
  path: '/api/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/e/$slug/',
  path: '/e/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizersIndexRoute = AdminOrganizersIndexRouteImport.update({
  id: '/organizers/',
  path: '/organizers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const ESlugEmbedRoute = ESlugEmbedRouteImport.update({
  id: '/e/$slug/embed',
  path: '/e/$slug/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugCheckoutRoute = ESlugCheckoutRouteImport.update({
  id: '/e/$slug/checkout',
  path: '/e/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1OrdersRoute = ApiV1OrdersRouteImport.update({
  id: '/api/v1/orders',
  path: '/api/v1/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSlugRoute = ApiOgSlugRouteImport.update({
  id: '/api/og/$slug',
  path: '/api/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGopayNotifyRoute = ApiGopayNotifyRouteImport.update({
  id: '/api/gopay/notify',
  path: '/api/gopay/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessWebhooksRoute = ApiCronProcessWebhooksRouteImport.update({
  id: '/api/cron/process-webhooks',
  path: '/api/cron/process-webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessWaitlistRoute = ApiCronProcessWaitlistRouteImport.update({
  id: '/api/cron/process-waitlist',
  path: '/api/cron/process-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessRefundsRoute = ApiCronProcessRefundsRouteImport.update({
  id: '/api/cron/process-refunds',
  path: '/api/cron/process-refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronProcessEmailRoute = ApiCronProcessEmailRouteImport.update({
  id: '/api/cron/process-email',
  path: '/api/cron/process-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronIssueInvoicesRoute = ApiCronIssueInvoicesRouteImport.update({
  id: '/api/cron/issue-invoices',
  path: '/api/cron/issue-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizersOrganizerIdRoute =
  AdminOrganizersOrganizerIdRouteImport.update({
    id: '/organizers/$organizerId',
    path: '/organizers/$organizerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdSalesRoute = AppEventsEventIdSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdPosSummaryRoute =
  AppEventsEventIdPosSummaryRouteImport.update({
    id: '/pos-summary',
    path: '/pos-summary',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdPosRoute = AppEventsEventIdPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const AppEventsEventIdManualOrderRoute =
  AppEventsEventIdManualOrderRouteImport.update({
    id: '/manual-order',
    path: '/manual-order',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdGuestlistRoute =
  AppEventsEventIdGuestlistRouteImport.update({
    id: '/guestlist',
    path: '/guestlist',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const AppEventsEventIdCheckinRoute = AppEventsEventIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)
const ApiV1EventsIdRoute = ApiV1EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1EventsRoute,
} as any)
const ApiSettlementsSettlementIdPdfRoute =
  ApiSettlementsSettlementIdPdfRouteImport.update({
    id: '/api/settlements/$settlementId/pdf',
    path: '/api/settlements/$settlementId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventsEventIdSalesCsvRoute =
  ApiEventsEventIdSalesCsvRouteImport.update({
    id: '/api/events/$eventId/sales-csv',
    path: '/api/events/$eventId/sales-csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEventsEventIdAttendeesCsvRoute =
  ApiEventsEventIdAttendeesCsvRouteImport.update({
    id: '/api/events/$eventId/attendees-csv',
    path: '/api/events/$eventId/attendees-csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminExportOrganizersDotcsvRoute =
  ApiAdminExportOrganizersDotcsvRouteImport.update({
    id: '/api/admin/export/organizers.csv',
    path: '/api/admin/export/organizers.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminExportOrdersDotcsvRoute =
  ApiAdminExportOrdersDotcsvRouteImport.update({
    id: '/api/admin/export/orders.csv',
    path: '/api/admin/export/orders.csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEventsEventIdOrdersOrderIdRoute =
  AppEventsEventIdOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)
const ApiV1EventsIdTicketsRoute = ApiV1EventsIdTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ApiV1EventsIdRoute,
} as any)
const ApiOrdersOrderIdTicketsTicketIdRoute =
  ApiOrdersOrderIdTicketsTicketIdRouteImport.update({
    id: '/api/orders/$orderId/tickets/$ticketId',
    path: '/api/orders/$orderId/tickets/$ticketId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersOrderIdTicketsTicketIdPassRoute =
  ApiOrdersOrderIdTicketsTicketIdPassRouteImport.update({
    id: '/pass',
    path: '/pass',
    getParentRoute: () => ApiOrdersOrderIdTicketsTicketIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/app': typeof AppRouteWithChildren
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/developers': typeof DevelopersRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/order/$id': typeof OrderIdRoute
  '/pos-receipt/$orderId': typeof PosReceiptOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/cron/issue-invoices': typeof ApiCronIssueInvoicesRoute
  '/api/cron/process-email': typeof ApiCronProcessEmailRoute
  '/api/cron/process-refunds': typeof ApiCronProcessRefundsRoute
  '/api/cron/process-waitlist': typeof ApiCronProcessWaitlistRoute
  '/api/cron/process-webhooks': typeof ApiCronProcessWebhooksRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug/embed': typeof ESlugEmbedRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/organizers/': typeof AdminOrganizersIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/admin/export/orders.csv': typeof ApiAdminExportOrdersDotcsvRoute
  '/api/admin/export/organizers.csv': typeof ApiAdminExportOrganizersDotcsvRoute
  '/api/events/$eventId/attendees-csv': typeof ApiEventsEventIdAttendeesCsvRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/api/settlements/$settlementId/pdf': typeof ApiSettlementsSettlementIdPdfRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/guestlist': typeof AppEventsEventIdGuestlistRoute
  '/app/events/$eventId/manual-order': typeof AppEventsEventIdManualOrderRoute
  '/app/events/$eventId/pos': typeof AppEventsEventIdPosRoute
  '/app/events/$eventId/pos-summary': typeof AppEventsEventIdPosSummaryRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRouteWithChildren
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRoute
  '/app/events/$eventId/orders/$orderId': typeof AppEventsEventIdOrdersOrderIdRoute
  '/api/orders/$orderId/tickets/$ticketId/pass': typeof ApiOrdersOrderIdTicketsTicketIdPassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/developers': typeof DevelopersRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/order/$id': typeof OrderIdRoute
  '/pos-receipt/$orderId': typeof PosReceiptOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/cron/issue-invoices': typeof ApiCronIssueInvoicesRoute
  '/api/cron/process-email': typeof ApiCronProcessEmailRoute
  '/api/cron/process-refunds': typeof ApiCronProcessRefundsRoute
  '/api/cron/process-waitlist': typeof ApiCronProcessWaitlistRoute
  '/api/cron/process-webhooks': typeof ApiCronProcessWebhooksRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug/embed': typeof ESlugEmbedRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/organizers': typeof AdminOrganizersIndexRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/api/admin/export/orders.csv': typeof ApiAdminExportOrdersDotcsvRoute
  '/api/admin/export/organizers.csv': typeof ApiAdminExportOrganizersDotcsvRoute
  '/api/events/$eventId/attendees-csv': typeof ApiEventsEventIdAttendeesCsvRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/api/settlements/$settlementId/pdf': typeof ApiSettlementsSettlementIdPdfRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/guestlist': typeof AppEventsEventIdGuestlistRoute
  '/app/events/$eventId/manual-order': typeof AppEventsEventIdManualOrderRoute
  '/app/events/$eventId/pos': typeof AppEventsEventIdPosRoute
  '/app/events/$eventId/pos-summary': typeof AppEventsEventIdPosSummaryRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/app/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRouteWithChildren
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRoute
  '/app/events/$eventId/orders/$orderId': typeof AppEventsEventIdOrdersOrderIdRoute
  '/api/orders/$orderId/tickets/$ticketId/pass': typeof ApiOrdersOrderIdTicketsTicketIdPassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ako-to-funguje': typeof AkoToFungujeRoute
  '/app': typeof AppRouteWithChildren
  '/cennik': typeof CennikRoute
  '/cookies': typeof CookiesRoute
  '/developers': typeof DevelopersRoute
  '/gdpr': typeof GdprRoute
  '/kontakt': typeof KontaktRoute
  '/login': typeof LoginRoute
  '/obchodne-podmienky': typeof ObchodnePodmienkyRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/checkin': typeof ApiCheckinRoute
  '/api/health': typeof ApiHealthRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/order/$id': typeof OrderIdRoute
  '/pos-receipt/$orderId': typeof PosReceiptOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/organizers/$organizerId': typeof AdminOrganizersOrganizerIdRoute
  '/api/cron/issue-invoices': typeof ApiCronIssueInvoicesRoute
  '/api/cron/process-email': typeof ApiCronProcessEmailRoute
  '/api/cron/process-refunds': typeof ApiCronProcessRefundsRoute
  '/api/cron/process-waitlist': typeof ApiCronProcessWaitlistRoute
  '/api/cron/process-webhooks': typeof ApiCronProcessWebhooksRoute
  '/api/gopay/notify': typeof ApiGopayNotifyRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/orders': typeof ApiV1OrdersRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/e/$slug/checkout': typeof ESlugCheckoutRoute
  '/e/$slug/embed': typeof ESlugEmbedRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/organizers/': typeof AdminOrganizersIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/api/admin/export/orders.csv': typeof ApiAdminExportOrdersDotcsvRoute
  '/api/admin/export/organizers.csv': typeof ApiAdminExportOrganizersDotcsvRoute
  '/api/events/$eventId/attendees-csv': typeof ApiEventsEventIdAttendeesCsvRoute
  '/api/events/$eventId/sales-csv': typeof ApiEventsEventIdSalesCsvRoute
  '/api/settlements/$settlementId/pdf': typeof ApiSettlementsSettlementIdPdfRoute
  '/api/v1/events/$id': typeof ApiV1EventsIdRouteWithChildren
  '/app/events/$eventId/checkin': typeof AppEventsEventIdCheckinRoute
  '/app/events/$eventId/guestlist': typeof AppEventsEventIdGuestlistRoute
  '/app/events/$eventId/manual-order': typeof AppEventsEventIdManualOrderRoute
  '/app/events/$eventId/pos': typeof AppEventsEventIdPosRoute
  '/app/events/$eventId/pos-summary': typeof AppEventsEventIdPosSummaryRoute
  '/app/events/$eventId/sales': typeof AppEventsEventIdSalesRoute
  '/app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/api/orders/$orderId/tickets/$ticketId': typeof ApiOrdersOrderIdTicketsTicketIdRouteWithChildren
  '/api/v1/events/$id/tickets': typeof ApiV1EventsIdTicketsRoute
  '/app/events/$eventId/orders/$orderId': typeof AppEventsEventIdOrdersOrderIdRoute
  '/api/orders/$orderId/tickets/$ticketId/pass': typeof ApiOrdersOrderIdTicketsTicketIdPassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ako-to-funguje'
    | '/app'
    | '/cennik'
    | '/cookies'
    | '/developers'
    | '/gdpr'
    | '/kontakt'
    | '/login'
    | '/obchodne-podmienky'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/admins'
    | '/admin/events'
    | '/admin/health'
    | '/admin/payouts'
    | '/admin/search'
    | '/api/checkin'
    | '/api/health'
    | '/app/developers'
    | '/app/settings'
    | '/app/settlements'
    | '/order/$id'
    | '/pos-receipt/$orderId'
    | '/admin/'
    | '/app/'
    | '/admin/orders/$orderId'
    | '/admin/organizers/$organizerId'
    | '/api/cron/issue-invoices'
    | '/api/cron/process-email'
    | '/api/cron/process-refunds'
    | '/api/cron/process-waitlist'
    | '/api/cron/process-webhooks'
    | '/api/gopay/notify'
    | '/api/og/$slug'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/openapi.json'
    | '/api/v1/orders'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug/embed'
    | '/admin/orders/'
    | '/admin/organizers/'
    | '/e/$slug/'
    | '/api/admin/export/orders.csv'
    | '/api/admin/export/organizers.csv'
    | '/api/events/$eventId/attendees-csv'
    | '/api/events/$eventId/sales-csv'
    | '/api/settlements/$settlementId/pdf'
    | '/api/v1/events/$id'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/guestlist'
    | '/app/events/$eventId/manual-order'
    | '/app/events/$eventId/pos'
    | '/app/events/$eventId/pos-summary'
    | '/app/events/$eventId/sales'
    | '/app/events/$eventId/'
    | '/api/orders/$orderId/tickets/$ticketId'
    | '/api/v1/events/$id/tickets'
    | '/app/events/$eventId/orders/$orderId'
    | '/api/orders/$orderId/tickets/$ticketId/pass'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ako-to-funguje'
    | '/cennik'
    | '/cookies'
    | '/developers'
    | '/gdpr'
    | '/kontakt'
    | '/login'
    | '/obchodne-podmienky'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/admins'
    | '/admin/events'
    | '/admin/health'
    | '/admin/payouts'
    | '/admin/search'
    | '/api/checkin'
    | '/api/health'
    | '/app/developers'
    | '/app/settings'
    | '/app/settlements'
    | '/order/$id'
    | '/pos-receipt/$orderId'
    | '/admin'
    | '/app'
    | '/admin/orders/$orderId'
    | '/admin/organizers/$organizerId'
    | '/api/cron/issue-invoices'
    | '/api/cron/process-email'
    | '/api/cron/process-refunds'
    | '/api/cron/process-waitlist'
    | '/api/cron/process-webhooks'
    | '/api/gopay/notify'
    | '/api/og/$slug'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/openapi.json'
    | '/api/v1/orders'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug/embed'
    | '/admin/orders'
    | '/admin/organizers'
    | '/e/$slug'
    | '/api/admin/export/orders.csv'
    | '/api/admin/export/organizers.csv'
    | '/api/events/$eventId/attendees-csv'
    | '/api/events/$eventId/sales-csv'
    | '/api/settlements/$settlementId/pdf'
    | '/api/v1/events/$id'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/guestlist'
    | '/app/events/$eventId/manual-order'
    | '/app/events/$eventId/pos'
    | '/app/events/$eventId/pos-summary'
    | '/app/events/$eventId/sales'
    | '/app/events/$eventId'
    | '/api/orders/$orderId/tickets/$ticketId'
    | '/api/v1/events/$id/tickets'
    | '/app/events/$eventId/orders/$orderId'
    | '/api/orders/$orderId/tickets/$ticketId/pass'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ako-to-funguje'
    | '/app'
    | '/cennik'
    | '/cookies'
    | '/developers'
    | '/gdpr'
    | '/kontakt'
    | '/login'
    | '/obchodne-podmienky'
    | '/register'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/admins'
    | '/admin/events'
    | '/admin/health'
    | '/admin/payouts'
    | '/admin/search'
    | '/api/checkin'
    | '/api/health'
    | '/app/developers'
    | '/app/settings'
    | '/app/settlements'
    | '/order/$id'
    | '/pos-receipt/$orderId'
    | '/admin/'
    | '/app/'
    | '/admin/orders/$orderId'
    | '/admin/organizers/$organizerId'
    | '/api/cron/issue-invoices'
    | '/api/cron/process-email'
    | '/api/cron/process-refunds'
    | '/api/cron/process-waitlist'
    | '/api/cron/process-webhooks'
    | '/api/gopay/notify'
    | '/api/og/$slug'
    | '/api/v1/events'
    | '/api/v1/me'
    | '/api/v1/openapi.json'
    | '/api/v1/orders'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/e/$slug/checkout'
    | '/e/$slug/embed'
    | '/admin/orders/'
    | '/admin/organizers/'
    | '/e/$slug/'
    | '/api/admin/export/orders.csv'
    | '/api/admin/export/organizers.csv'
    | '/api/events/$eventId/attendees-csv'
    | '/api/events/$eventId/sales-csv'
    | '/api/settlements/$settlementId/pdf'
    | '/api/v1/events/$id'
    | '/app/events/$eventId/checkin'
    | '/app/events/$eventId/guestlist'
    | '/app/events/$eventId/manual-order'
    | '/app/events/$eventId/pos'
    | '/app/events/$eventId/pos-summary'
    | '/app/events/$eventId/sales'
    | '/app/events/$eventId/'
    | '/api/orders/$orderId/tickets/$ticketId'
    | '/api/v1/events/$id/tickets'
    | '/app/events/$eventId/orders/$orderId'
    | '/api/orders/$orderId/tickets/$ticketId/pass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AkoToFungujeRoute: typeof AkoToFungujeRoute
  AppRoute: typeof AppRouteWithChildren
  CennikRoute: typeof CennikRoute
  CookiesRoute: typeof CookiesRoute
  DevelopersRoute: typeof DevelopersRoute
  GdprRoute: typeof GdprRoute
  KontaktRoute: typeof KontaktRoute
  LoginRoute: typeof LoginRoute
  ObchodnePodmienkyRoute: typeof ObchodnePodmienkyRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCheckinRoute: typeof ApiCheckinRoute
  ApiHealthRoute: typeof ApiHealthRoute
  OrderIdRoute: typeof OrderIdRoute
  PosReceiptOrderIdRoute: typeof PosReceiptOrderIdRoute
  ApiCronIssueInvoicesRoute: typeof ApiCronIssueInvoicesRoute
  ApiCronProcessEmailRoute: typeof ApiCronProcessEmailRoute
  ApiCronProcessRefundsRoute: typeof ApiCronProcessRefundsRoute
  ApiCronProcessWaitlistRoute: typeof ApiCronProcessWaitlistRoute
  ApiCronProcessWebhooksRoute: typeof ApiCronProcessWebhooksRoute
  ApiGopayNotifyRoute: typeof ApiGopayNotifyRoute
  ApiOgSlugRoute: typeof ApiOgSlugRoute
  ApiV1EventsRoute: typeof ApiV1EventsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1OrdersRoute: typeof ApiV1OrdersRoute
  ESlugCheckoutRoute: typeof ESlugCheckoutRoute
  ESlugEmbedRoute: typeof ESlugEmbedRoute
  ESlugIndexRoute: typeof ESlugIndexRoute
  ApiAdminExportOrdersDotcsvRoute: typeof ApiAdminExportOrdersDotcsvRoute
  ApiAdminExportOrganizersDotcsvRoute: typeof ApiAdminExportOrganizersDotcsvRoute
  ApiEventsEventIdAttendeesCsvRoute: typeof ApiEventsEventIdAttendeesCsvRoute
  ApiEventsEventIdSalesCsvRoute: typeof ApiEventsEventIdSalesCsvRoute
  ApiSettlementsSettlementIdPdfRoute: typeof ApiSettlementsSettlementIdPdfRoute
  ApiOrdersOrderIdTicketsTicketIdRoute: typeof ApiOrdersOrderIdTicketsTicketIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obchodne-podmienky': {
      id: '/obchodne-podmienky'
      path: '/obchodne-podmienky'
      fullPath: '/obchodne-podmienky'
      preLoaderRoute: typeof ObchodnePodmienkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ako-to-funguje': {
      id: '/ako-to-funguje'
      path: '/ako-to-funguje'
      fullPath: '/ako-to-funguje'
      preLoaderRoute: typeof AkoToFungujeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pos-receipt/$orderId': {
      id: '/pos-receipt/$orderId'
      path: '/pos-receipt/$orderId'
      fullPath: '/pos-receipt/$orderId'
      preLoaderRoute: typeof PosReceiptOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settlements': {
      id: '/app/settlements'
      path: '/settlements'
      fullPath: '/app/settlements'
      preLoaderRoute: typeof AppSettlementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/developers': {
      id: '/app/developers'
      path: '/developers'
      fullPath: '/app/developers'
      preLoaderRoute: typeof AppDevelopersRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkin': {
      id: '/api/checkin'
      path: '/api/checkin'
      fullPath: '/api/checkin'
      preLoaderRoute: typeof ApiCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/e/$slug'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizers/': {
      id: '/admin/organizers/'
      path: '/organizers'
      fullPath: '/admin/organizers/'
      preLoaderRoute: typeof AdminOrganizersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$slug/embed': {
      id: '/e/$slug/embed'
      path: '/e/$slug/embed'
      fullPath: '/e/$slug/embed'
      preLoaderRoute: typeof ESlugEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/checkout': {
      id: '/e/$slug/checkout'
      path: '/e/$slug/checkout'
      fullPath: '/e/$slug/checkout'
      preLoaderRoute: typeof ESlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/orders': {
      id: '/api/v1/orders'
      path: '/api/v1/orders'
      fullPath: '/api/v1/orders'
      preLoaderRoute: typeof ApiV1OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$slug': {
      id: '/api/og/$slug'
      path: '/api/og/$slug'
      fullPath: '/api/og/$slug'
      preLoaderRoute: typeof ApiOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gopay/notify': {
      id: '/api/gopay/notify'
      path: '/api/gopay/notify'
      fullPath: '/api/gopay/notify'
      preLoaderRoute: typeof ApiGopayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-webhooks': {
      id: '/api/cron/process-webhooks'
      path: '/api/cron/process-webhooks'
      fullPath: '/api/cron/process-webhooks'
      preLoaderRoute: typeof ApiCronProcessWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-waitlist': {
      id: '/api/cron/process-waitlist'
      path: '/api/cron/process-waitlist'
      fullPath: '/api/cron/process-waitlist'
      preLoaderRoute: typeof ApiCronProcessWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-refunds': {
      id: '/api/cron/process-refunds'
      path: '/api/cron/process-refunds'
      fullPath: '/api/cron/process-refunds'
      preLoaderRoute: typeof ApiCronProcessRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-email': {
      id: '/api/cron/process-email'
      path: '/api/cron/process-email'
      fullPath: '/api/cron/process-email'
      preLoaderRoute: typeof ApiCronProcessEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/issue-invoices': {
      id: '/api/cron/issue-invoices'
      path: '/api/cron/issue-invoices'
      fullPath: '/api/cron/issue-invoices'
      preLoaderRoute: typeof ApiCronIssueInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizers/$organizerId': {
      id: '/admin/organizers/$organizerId'
      path: '/organizers/$organizerId'
      fullPath: '/admin/organizers/$organizerId'
      preLoaderRoute: typeof AdminOrganizersOrganizerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/events/$eventId/': {
      id: '/app/events/$eventId/'
      path: '/'
      fullPath: '/app/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/sales': {
      id: '/app/events/$eventId/sales'
      path: '/sales'
      fullPath: '/app/events/$eventId/sales'
      preLoaderRoute: typeof AppEventsEventIdSalesRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/pos-summary': {
      id: '/app/events/$eventId/pos-summary'
      path: '/pos-summary'
      fullPath: '/app/events/$eventId/pos-summary'
      preLoaderRoute: typeof AppEventsEventIdPosSummaryRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/pos': {
      id: '/app/events/$eventId/pos'
      path: '/pos'
      fullPath: '/app/events/$eventId/pos'
      preLoaderRoute: typeof AppEventsEventIdPosRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/manual-order': {
      id: '/app/events/$eventId/manual-order'
      path: '/manual-order'
      fullPath: '/app/events/$eventId/manual-order'
      preLoaderRoute: typeof AppEventsEventIdManualOrderRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/guestlist': {
      id: '/app/events/$eventId/guestlist'
      path: '/guestlist'
      fullPath: '/app/events/$eventId/guestlist'
      preLoaderRoute: typeof AppEventsEventIdGuestlistRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/app/events/$eventId/checkin': {
      id: '/app/events/$eventId/checkin'
      path: '/checkin'
      fullPath: '/app/events/$eventId/checkin'
      preLoaderRoute: typeof AppEventsEventIdCheckinRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/api/v1/events/$id': {
      id: '/api/v1/events/$id'
      path: '/$id'
      fullPath: '/api/v1/events/$id'
      preLoaderRoute: typeof ApiV1EventsIdRouteImport
      parentRoute: typeof ApiV1EventsRoute
    }
    '/api/settlements/$settlementId/pdf': {
      id: '/api/settlements/$settlementId/pdf'
      path: '/api/settlements/$settlementId/pdf'
      fullPath: '/api/settlements/$settlementId/pdf'
      preLoaderRoute: typeof ApiSettlementsSettlementIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$eventId/sales-csv': {
      id: '/api/events/$eventId/sales-csv'
      path: '/api/events/$eventId/sales-csv'
      fullPath: '/api/events/$eventId/sales-csv'
      preLoaderRoute: typeof ApiEventsEventIdSalesCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$eventId/attendees-csv': {
      id: '/api/events/$eventId/attendees-csv'
      path: '/api/events/$eventId/attendees-csv'
      fullPath: '/api/events/$eventId/attendees-csv'
      preLoaderRoute: typeof ApiEventsEventIdAttendeesCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export/organizers.csv': {
      id: '/api/admin/export/organizers.csv'
      path: '/api/admin/export/organizers.csv'
      fullPath: '/api/admin/export/organizers.csv'
      preLoaderRoute: typeof ApiAdminExportOrganizersDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/export/orders.csv': {
      id: '/api/admin/export/orders.csv'
      path: '/api/admin/export/orders.csv'
      fullPath: '/api/admin/export/orders.csv'
      preLoaderRoute: typeof ApiAdminExportOrdersDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/$eventId/orders/$orderId': {
      id: '/app/events/$eventId/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/app/events/$eventId/orders/$orderId'
      preLoaderRoute: typeof AppEventsEventIdOrdersOrderIdRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
    '/api/v1/events/$id/tickets': {
      id: '/api/v1/events/$id/tickets'
      path: '/tickets'
      fullPath: '/api/v1/events/$id/tickets'
      preLoaderRoute: typeof ApiV1EventsIdTicketsRouteImport
      parentRoute: typeof ApiV1EventsIdRoute
    }
    '/api/orders/$orderId/tickets/$ticketId': {
      id: '/api/orders/$orderId/tickets/$ticketId'
      path: '/api/orders/$orderId/tickets/$ticketId'
      fullPath: '/api/orders/$orderId/tickets/$ticketId'
      preLoaderRoute: typeof ApiOrdersOrderIdTicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/tickets/$ticketId/pass': {
      id: '/api/orders/$orderId/tickets/$ticketId/pass'
      path: '/pass'
      fullPath: '/api/orders/$orderId/tickets/$ticketId/pass'
      preLoaderRoute: typeof ApiOrdersOrderIdTicketsTicketIdPassRouteImport
      parentRoute: typeof ApiOrdersOrderIdTicketsTicketIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrganizersOrganizerIdRoute: typeof AdminOrganizersOrganizerIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminOrganizersIndexRoute: typeof AdminOrganizersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrganizersOrganizerIdRoute: AdminOrganizersOrganizerIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminOrganizersIndexRoute: AdminOrganizersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdCheckinRoute: typeof AppEventsEventIdCheckinRoute
  AppEventsEventIdGuestlistRoute: typeof AppEventsEventIdGuestlistRoute
  AppEventsEventIdManualOrderRoute: typeof AppEventsEventIdManualOrderRoute
  AppEventsEventIdPosRoute: typeof AppEventsEventIdPosRoute
  AppEventsEventIdPosSummaryRoute: typeof AppEventsEventIdPosSummaryRoute
  AppEventsEventIdSalesRoute: typeof AppEventsEventIdSalesRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppEventsEventIdOrdersOrderIdRoute: typeof AppEventsEventIdOrdersOrderIdRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdCheckinRoute: AppEventsEventIdCheckinRoute,
  AppEventsEventIdGuestlistRoute: AppEventsEventIdGuestlistRoute,
  AppEventsEventIdManualOrderRoute: AppEventsEventIdManualOrderRoute,
  AppEventsEventIdPosRoute: AppEventsEventIdPosRoute,
  AppEventsEventIdPosSummaryRoute: AppEventsEventIdPosSummaryRoute,
  AppEventsEventIdSalesRoute: AppEventsEventIdSalesRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppEventsEventIdOrdersOrderIdRoute: AppEventsEventIdOrdersOrderIdRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppDevelopersRoute: typeof AppDevelopersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSettlementsRoute: typeof AppSettlementsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDevelopersRoute: AppDevelopersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSettlementsRoute: AppSettlementsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1EventsIdRouteChildren {
  ApiV1EventsIdTicketsRoute: typeof ApiV1EventsIdTicketsRoute
}

const ApiV1EventsIdRouteChildren: ApiV1EventsIdRouteChildren = {
  ApiV1EventsIdTicketsRoute: ApiV1EventsIdTicketsRoute,
}

const ApiV1EventsIdRouteWithChildren = ApiV1EventsIdRoute._addFileChildren(
  ApiV1EventsIdRouteChildren,
)

interface ApiV1EventsRouteChildren {
  ApiV1EventsIdRoute: typeof ApiV1EventsIdRouteWithChildren
}

const ApiV1EventsRouteChildren: ApiV1EventsRouteChildren = {
  ApiV1EventsIdRoute: ApiV1EventsIdRouteWithChildren,
}

const ApiV1EventsRouteWithChildren = ApiV1EventsRoute._addFileChildren(
  ApiV1EventsRouteChildren,
)

interface ApiOrdersOrderIdTicketsTicketIdRouteChildren {
  ApiOrdersOrderIdTicketsTicketIdPassRoute: typeof ApiOrdersOrderIdTicketsTicketIdPassRoute
}

const ApiOrdersOrderIdTicketsTicketIdRouteChildren: ApiOrdersOrderIdTicketsTicketIdRouteChildren =
  {
    ApiOrdersOrderIdTicketsTicketIdPassRoute:
      ApiOrdersOrderIdTicketsTicketIdPassRoute,
  }

const ApiOrdersOrderIdTicketsTicketIdRouteWithChildren =
  ApiOrdersOrderIdTicketsTicketIdRoute._addFileChildren(
    ApiOrdersOrderIdTicketsTicketIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AkoToFungujeRoute: AkoToFungujeRoute,
  AppRoute: AppRouteWithChildren,
  CennikRoute: CennikRoute,
  CookiesRoute: CookiesRoute,
  DevelopersRoute: DevelopersRoute,
  GdprRoute: GdprRoute,
  KontaktRoute: KontaktRoute,
  LoginRoute: LoginRoute,
  ObchodnePodmienkyRoute: ObchodnePodmienkyRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCheckinRoute: ApiCheckinRoute,
  ApiHealthRoute: ApiHealthRoute,
  OrderIdRoute: OrderIdRoute,
  PosReceiptOrderIdRoute: PosReceiptOrderIdRoute,
  ApiCronIssueInvoicesRoute: ApiCronIssueInvoicesRoute,
  ApiCronProcessEmailRoute: ApiCronProcessEmailRoute,
  ApiCronProcessRefundsRoute: ApiCronProcessRefundsRoute,
  ApiCronProcessWaitlistRoute: ApiCronProcessWaitlistRoute,
  ApiCronProcessWebhooksRoute: ApiCronProcessWebhooksRoute,
  ApiGopayNotifyRoute: ApiGopayNotifyRoute,
  ApiOgSlugRoute: ApiOgSlugRoute,
  ApiV1EventsRoute: ApiV1EventsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1OrdersRoute: ApiV1OrdersRoute,
  ESlugCheckoutRoute: ESlugCheckoutRoute,
  ESlugEmbedRoute: ESlugEmbedRoute,
  ESlugIndexRoute: ESlugIndexRoute,
  ApiAdminExportOrdersDotcsvRoute: ApiAdminExportOrdersDotcsvRoute,
  ApiAdminExportOrganizersDotcsvRoute: ApiAdminExportOrganizersDotcsvRoute,
  ApiEventsEventIdAttendeesCsvRoute: ApiEventsEventIdAttendeesCsvRoute,
  ApiEventsEventIdSalesCsvRoute: ApiEventsEventIdSalesCsvRoute,
  ApiSettlementsSettlementIdPdfRoute: ApiSettlementsSettlementIdPdfRoute,
  ApiOrdersOrderIdTicketsTicketIdRoute:
    ApiOrdersOrderIdTicketsTicketIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
