-- Phase 22 Block 3e — per-scan idempotency for the offline check-in app.
--
-- The Ticketio Scan app queues admissions made without a network and replays
-- them through POST /api/checkin. Delivery is at-least-once: if the server
-- commits a scan but the response is lost, the app sends it again. Ticket-level
-- idempotency is not enough for that case — on an event with allow_reentry the
-- replay would be recorded as an extra entry, and the organizer would see more
-- entries than really happened.
--
-- client_scan_id is a uuid generated by the app at the moment of the scan and
-- kept with the queued entry, so the retry carries the SAME id. The server
-- returns the original outcome instead of writing a second row.
--
-- Nullable: the web scanner does not send it, and historical rows have none.

alter table checkin_log
  add column if not exists client_scan_id uuid;

comment on column checkin_log.client_scan_id is
  'Client-generated id of one scan (Ticketio Scan app). Makes replay of a queued offline check-in idempotent at scan level, not just at ticket level. Null for web scans and historical rows.';

-- Partial unique index: one row per scan, while allowing unlimited nulls.
create unique index if not exists checkin_log_client_scan_id_key
  on checkin_log (client_scan_id)
  where client_scan_id is not null;
