// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upymwphlrkxcegnyslky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVweW13cGhscmt4Y2VnbnlzbGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxMTMxMzMsImV4cCI6MjA5OTY4OTEzM30.iydVpeFkHOjACc4_U6q_NtUwPDrel2QHu0UuL9nL3pA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});